name: todo_ui
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_onboarding_slider: ^1.0.11
  convex_bottom_bar: ^3.2.0
  d_chart: ^2.6.9
  neon_circular_timer: ^0.0.7
  charts_flutter: ^0.12.0
  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/intologo.jpg
    - assets/icons/intro.png

  fonts:
    - family: Latoname
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Italic.ttf
  # fonts:
    - family: Poppins
      fonts:
  #       # - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/Poppins/Poppins-Bold.ttf
  #       # - asset: assets/fonts/Lato-Italic.ttf